### ISSUE TITLE
Update "People" on openworm.org

### ISSUE THREAD

**Issue by balicea** [openworm/org.openworm.website#100]
Sort list of senior contributors (http://www.openworm.org/people.html) linearly with affiliations, links, and pics (if available). 

Also, "Bradly Alicea" is misspelled and the link needs to be updated.

**Comment by MichaelCurrie** [comment]
"Bradly Alicea" name fixed by https://github.com/openworm/org.openworm.website/commit/ae834085b6d778855facdf6afdb129f6428763d6.

**Comment by MichaelCurrie** [comment]
**Content to update**

Board of Directors
Scientific Advisory Panel (please rename from "Scientific Advisory Board")
OpenWorm Fellows
Senior Contributors
Contributors

Here is a link to pictures and updated staff heirarchy: https://docs.google.com/document/d/1rRAInsQuwHv51S7OmhUUOxSlkybxneFuXWjqyLmZoBY/edit?usp=sharing

**Styling changes**

1. Add pictures for all people except contributors.  No biography is needed for any of the people, I think, just their name and picture.

2. Change layout to this: https://startbootstrap.com/template-overviews/round-about/

![image](https://user-images.githubusercontent.com/5267078/27522686-d0f718a0-59dc-11e7-8c38-21b0d571068e.png)

(Or if you are feeling amazing, one of these ideas: https://speckyboy.com/50-webpage-layouts-showcasing-company-teams-employees/)

**Comment by geekSiddharth** [comment]
Are we including social media or other URLs?

**Comment by gidili** [comment]
@geekSiddharth urls depend on each individual, whatever they want linked I'd say

**Comment by geekSiddharth** [comment]
What about job title/positon?

**Comment by gidili** [comment]
@geekSiddharth I think that's optional as most people won't have formal titles on there, I would default to no title but make it possible to have something (some people have titles like the chairman of the board for example and few others) and that can be edited once it's in place

**Comment by geekSiddharth** [comment]
How is this coming out? 
![image](https://user-images.githubusercontent.com/21156678/27661449-eb2eb83e-5c77-11e7-905f-88bcf0fef6e5.png)

**Comment by gidili** [comment]
Looks great! 👍

**Comment by geekSiddharth** [comment]
A tagline for OpenWorm Fellows?

**Comment by tarelli** [comment]
@geekSiddharth Looks good! We need also to add Lucy Rogers http://lucyrogers.com/ https://twitter.com/drlucyrogers to the board of directors (just appointed), cheers!

**Comment by slarson** [comment]
"Inspiring minds and helpful hands" for tagline for Fellows is my vote

**Comment by geekSiddharth** [comment]
Can I get edit access to that google doc? I'm not able to copy the images right now. 
It would save me a lot of time in the senior contributor section.

**Comment by tarelli** [comment]
You should have access now

**Comment by tarelli** [comment]
@geekSiddharth Started reviewing:

- [ ] Some images are missing, pointing to a jpg while the png is there
```
people.html:438 GET http://localhost:8888/img/beaubuck.jpg 404 (Not Found)
people.html:477 GET http://localhost:8888/img/lucy.jpg 404 (Not Found)
people.html:618 GET http://localhost:8888/img/images/image17.jpg 404 (Not Found)
people.html:630 GET http://localhost:8888/img/images/image15.jpg 404 (Not Found)
people.html:639 GET http://localhost:8888/img/images/image13.jpg 404 (Not Found)
people.html:649 GET http://localhost:8888/img/images/image20.jpg 404 (Not Found)
people.html:679 GET http://localhost:8888/img/images/image8.jpg 404 (Not Found)
```
- [ ] All images of same size, I'd say the size of the senior contributors is good so that even the board of director they will all fit in a row
- [ ] Put all pics in a folder img/biopics (not images) so they are easier to find/update
- [ ] Name the pictures after the person instead of imagexxx
- [ ] Drop the Dr
- [ ] Chairman on a separate line like it was before
- [ ] Better picture for Bradly (http://users.clas.ufl.edu/cmulligan/Webpage/Bradly.jpg ?)
- [ ] Smaller slack logo, height 80px
- [ ] Hide Google URL, make the word form clickable
