### ISSUE TITLE
Unhide "External Resources" section of Science subpage

### ISSUE THREAD

**Issue by balicea** [openworm/org.openworm.website#101]
Concern: major resources (databases, data, and tools) are hidden on current Science page (http://www.openworm.org/science.html#other).

![sci-resources](https://cloud.githubusercontent.com/assets/2716218/22347030/e55232a8-e3cb-11e6-9012-7c081cbb9f82.png)

Solution: can this be a standalone page with a more prominent link from the front page (e.g. Open Data and Tools)?

**Comment by MichaelCurrie** [comment]
The front page is already pretty occupied with stuff.  I agree that this could be more exposed.  If someone can come up with a specific plan, I agree we should reopen this.  I will close just to keep the focus on extremely actionable items.
