### ISSUE TITLE
Add "publications" page to science side menu

### ISSUE THREAD

**Issue by balicea** [openworm/org.openworm.website#102]
The Publications page (http://www.openworm.org/publications.html) should be more prominently featured as a link from the front page. As of now, it links from the Science page, and should be made more explicit to first-time visitors.

In a related fashion, the social media connections should also be made prominent on the front page (as icons).

**Comment by MichaelCurrie** [comment]
**Sub-task 1**

Add a link called "Publications" to http://www.openworm.org/publications.html from the sidebar menu at http://www.openworm.org/science.html:

![image](https://user-images.githubusercontent.com/5267078/27539881-0fda3a6a-5a33-11e7-9b53-6a17d5680850.png)

**Sub-task 2**
Add social media connections as icons.  This is done already:

![image](https://user-images.githubusercontent.com/5267078/27539951-4ae5c26e-5a33-11e7-8246-489b87f447f2.png)

**Comment by susybiasdesign** [comment]
Hi, I can do this quick task. Do you still need help?

**Comment by tarelli** [comment]
Thanks @susybiasdesign merged now!
