### ISSUE TITLE
Add description about the TEDx talk

### ISSUE THREAD

**Issue by geekSiddharth** [openworm/org.openworm.website#107]
The icon of the TEDx doesn't make much sense by itself. I think adding a one line description about the video would be better. We can make that an embedded video too.

**Comment by MichaelCurrie** [comment]
I agree.  An embedded video would be awesome.

TedX Bangalore: https://www.youtube.com/watch?v=RY2-0-QsuTE
TedX Vienna: https://www.youtube.com/watch?v=EKopW86CCJo

**Comment by MichaelCurrie** [comment]
Handled by @geekSiddharth with https://github.com/openworm/org.openworm.website/pull/109

**Comment by notsambeck** [comment]
Will this automatically sync to the live site at some point in the future? Trying to make sure I'm working with current versions

**Comment by gidili** [comment]
@notsambeck no, we push it manually from eclipse google plugin (it's literally one click). I see the PR for this was merged to master, what happens now is we test it locally and then if looks good we deploy. I can look at it today 👍

**Comment by gidili** [comment]
Oh I see what's going on, the link was hardcoded to openworm.org instead of being relative so it's linking to the deployed version. Looking good now. 

Made few changes: https://github.com/openworm/org.openworm.website/commit/ca476b89978784b5bfe55a704888de052769a5ea
