### ISSUE TITLE
Add core team picture to "people" page

### ISSUE THREAD

**Issue by gidili** [openworm/org.openworm.website#18]
We took a few pictures of the core team in Paris. Let's pick the best ones and put it on the people's page under core team.

**Comment by MichaelCurrie** [comment]
Good idea!  And now, who has pictures from the November 2014 meeting?  Sadly these are my only two: 
  
![2014-11-06 18 08 11](https://cloud.githubusercontent.com/assets/5267078/11160680/4b6cbef2-8a2a-11e5-8935-bce58f38fd53.jpg)

![2014-11-05 23 08 10](https://cloud.githubusercontent.com/assets/5267078/11160662/18dff6fc-8a2a-11e5-9a0f-6b9ad2cbfe05.jpg)

**Comment by MichaelCurrie** [comment]
Duplicate of https://github.com/openworm/org.openworm.website/issues/100
