### ISSUE TITLE
Jubotron arrows disabled for narrow screens

### ISSUE THREAD

**Issue by mwatts15** [openworm/org.openworm.website#41]
For page widths of less than 767 pixels, the navigation arrows in the 'DIV.jumbotron.masthead' element stop functioning.
![screen shot 2014-05-05 at 10 48 20](https://cloud.githubusercontent.com/assets/1487560/2917640/416fdc20-d6c8-11e3-8b29-593bf32ac222.png)

**Comment by MichaelCurrie** [comment]
I can replicate this issue.  It looks like the code to manage these navigation arrows is called "carousel".

Our carousel code is here: https://github.com/openworm/org.openworm.website/blob/master/war/js/bootstrap.js#L241

That code is taken from http://twitter.github.com/bootstrap/javascript.html#carousel, or rather https://github.com/twbs/bootstrap

Our version is 2.2.1; the latest is 3.3.6.  If we upgraded it would perhaps fix this issue.  I'll leave this to a JS guy, which I am not.

**Comment by MichaelCurrie** [comment]
I'm going to close this to keep focus on more urgent issues but someone more ambitious could re-open this and fix it.
