### ISSUE TITLE
Link to list of Kickstarter backers

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.openworm.website#44]
From here: http://www.openworm.org/supporters.html

**Comment by MichaelCurrie** [comment]
@pgleeson I'm not sure what this issue means.  The http://www.openworm.org/supporters.html page includes a list of all Kickstarter backers as well as a link back to the original Kickstarter.

Given that you opened this issue back in May 2014 it may be that the issue you saw was subsequently handled.  So I'll close this - feel free to open it again and clarify.  Thanks!

**Comment by gidili** [comment]
@MichaelCurrie yes this was completed but we forgot abut the issue! Thanks for the cleanup! :)
