### ISSUE TITLE
Enable http://www.openworm.org/science etc.

### ISSUE THREAD

**Issue by pgleeson** [openworm/org.openworm.website#49]
While http://www.openworm.org/science.html works, http://www.openworm.org/science doesn't, but the latter would be better to put in emails, etc. 

Also http://science.openworm.org if possible...

Same goes for some other pages, e.g. http://www.openworm.org/about

**Comment by MichaelCurrie** [comment]
www.openworm.org/science works now; handled by 5a7aec85f387cb83badbccd24a280bfe40ca00e3

(not science.openworm.org or www.openworm.org/about, though)

**Comment by pgleeson** [comment]
http://www.openworm.org/science is not working for me...

**Comment by MichaelCurrie** [comment]
Yeah, me neither as I look at it now.  It worked when I tested it locally.

**Comment by MichaelCurrie** [comment]
Wait, `http://www.openworm.org/science/` works for me.  Not sure how to get it to work without the final forward slash.
