### ISSUE TITLE
If the site is just a simple static site you can use github pages free

### ISSUE THREAD

**Issue by amerikan** [openworm/org.openworm.website#52]
This issue is a suggestion, not a bug. :)

Docs: https://pages.github.com/

I can help setting it up it's rather easy. The github repository itself serves as the code of the site. So when there's a change to make it's a matter of just pulling a request to update it.

**Comment by MichaelCurrie** [comment]
Thanks for the suggestion!

However, it seems we already have the advantage you mention, in the sense that if we make a commit to this repository, it's immediately reflected in our www.openworm.org website.  Given limited volunteer bandwidth to make changes I'm going to mark this issue as handled.  Someone else can feel free to disagree and reopen this issue, however.

**Comment by MichaelCurrie** [comment]
@slarson I have re-opened this issue as it appears there is a renewed interest in doing this.  Thanks to @amerikan for the original suggestion!

**Comment by MichaelCurrie** [comment]
I'm going to close this again since there was no movement in this direction.
