### ISSUE TITLE
Test/Fix broken links (Optimal neuron for instance)

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/org.openworm.website#62]
- [x] https://openworm.github.io/Smoothed-Particle-Hydrodynamics/
- [x] http://optimal-neuron.readthedocs.io/en/0.5/installation.html
- [x] http://openworm.github.io/Smoothed-Particle-Hydrodynamics/
- [x] http://www.linkedin.com/pub/christian-grove/a/396/562
- [x] http://nouvellesaujourdhui.com/les-ascarides-lombricoides-se-tiennent-le-premier-role-dans-openworm-un-simulateur-de-vie-artificielle/
- [x] http://www.linkedin.com/pub/sergey-khayrulin/31/2a7/452
- [x] http://www.linkedin.com/in/stephendavidlarson
- [x] http://www.linkedin.com/in/crystinslade
- [x] http://www.linkedin.com/pub/daniel-knudsen/53/45a/bb4
- [x] http://www.linkedin.com/pub/david-dalrymple/1a/205/b9b
- [x] http://molbiosci.rutgers.edu/faculty/taylor.html
- [x] http://www.dimitar-shterionov.com
- [x] http://www.linkedin.com/pub/jay-s-coggan/27/215/741
- [x] http://www.linkedin.com/in/jhurliman
- [x] http://www.comp.leeds.ac.uk/jboyle/
- [x] http://www.linkedin.com/pub/jinze-yu/28/47/371
- [x] http://www.linkedin.com/pub/marius-buibas/6/981/a51
- [x] http://www.linkedin.com/in/mariuszksasinski
- [x] http://www.linkedin.com/in/richardstoner
- [x] http://www.linkedin.com/pub/steven-j-cook/5b/436/b23
- [x] http://www.linkedin.com/in/timothybusbice
- [x] http://www.openworm.org/img/osblogo.jpg
- [x] http://www.nature.com/nmeth/journal/v10/n9/full/nmeth.2560.html
- [x] http://www.mfrancislab.org/interests.html
- [x] http://tock.bcgsc.ca/cgi-bin/sage170
- [x] https://portal.g-node.org/gpu-workshop-2012/
- [x] https://www.neuroml.org/robots.txt
- [x] https://www.incf.orgcommunity/people/pgleeson/person_view
- [x] http://bgypc059.leeds.ac.uk/~webuser/databaseintro.htm

**Comment by slarson** [comment]
[Dead Link Checker reports.pdf](https://github.com/openworm/org.openworm.website/files/263939/Dead.Link.Checker.reports.pdf)

**Comment by slarson** [comment]
Also: openworm/OpenWorm#221
