### ISSUE TITLE
OpenWorm Browser iTunes App available only in the USA Store

### ISSUE THREAD

**Issue by cheelee** [openworm/org.openworm.website#66]
Apparently Singapore-based access to iTunes blocks the download of the OpenWorm Browser App. Is this by design, or are there any other impediments to opening access to all parts of the world?

**Comment by slarson** [comment]
Interesting -- it probably required extra settings.  For now though we are deprecating the iphone app in favor of the web app http://browser.openworm.org -- so this should work everywhere.
