### ISSUE TITLE
Have movement.openworm.org point to 52.220.51.117

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/org.openworm.website#68]
What provider currently handles DNS routing?

Perhaps we could migrate to Route53, so that I can configure movement.openworm.org to be the address for the [https://github.com/openworm/open-worm-analysis-toolbox](Open Worm Analysis Toolbox) web interface.

e.g. @gidili do you know?  Thanks!

**Comment by gidili** [comment]
I do not - I think it's either @tarelli or @slarson who know this one!

**Comment by tarelli** [comment]
It's godaddy, no need to migrate, it supports forwarding. It's @slarson account if I remember correctly.

**Comment by slarson** [comment]
@MichaelCurrie on whatever provider you are serving from, you'll need to look up how to map to a custom domain.  That should contain what DNS information needs to appear to map it.  I'll need the DNS information and then I can map it in on openworm.org.

**Comment by tarelli** [comment]
Another option might be a simple forward to a URL from a subdomain, I did that for some geppetto ones.

**Comment by slarson** [comment]
Either way, I don't mind.  I think the DNS route avoids an extra hop which
speeds up total load time of the page but I'm ready to do whatever is
easiest.
ᐧ

On Thu, Jun 2, 2016 at 10:57 AM, Matteo Cantarelli <notifications@github.com

**Comment by slarson** [comment]
Reference: open-worm-analysis-toolbox#193

**Comment by slarson** [comment]
Pretty sure its done now; but the IP is not up, so nothing shows up at the address.

**Comment by MichaelCurrie** [comment]
Port 22 (SSH) will work but I don't always have the server running on port 80 (HTTP) right now.  (In development).

Thanks!  Works great.
