### ISSUE TITLE
Update events page

### ISSUE THREAD

**Issue by slarson** [openworm/org.openworm.website#73]
events.html is two years old now.. maybe better to remove or find a different way to represent events?  Maybe a link to the public calendar?

**Comment by MichaelCurrie** [comment]
@slarson where is this public calendar?  Here is the current page: http://www.openworm.org/events.html

Perhaps you could share the email newsletter content here in this issue so that the person handling this issue will have some content to add.

**Comment by MichaelCurrie** [comment]
Duplicate of https://github.com/openworm/org.openworm.website/issues/99
