### ISSUE TITLE
Icons have shrunk

### ISSUE THREAD

**Issue by slarson** [openworm/org.openworm.website#81]
The little tiny film strip is what I'm referring to: 

I'm seeing this in several places across the site.

![screen shot 2016-09-02 at 9 04 50 am](https://cloud.githubusercontent.com/assets/1037756/18196940/600cad50-70ec-11e6-88d5-1830aacc3298.png)

**Comment by amerikan** [comment]
Seems like you guys updated font-awesome here: https://github.com/openworm/org.openworm.website/commit/5d1d8026a21da0f1efbbd372cbbf687a22b32546

In the newest fontawesome you're suppose to use:
> To increase icon sizes relative to their container, use the fa-lg (33% increase), fa-2x, fa-3x, fa-4x, or fa-5x classes. 

So I see a lot of `fa-xxl` (should be `fa-2x`) among other weird ones.
