### ISSUE TITLE
Make people page more prominent

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/org.openworm.website#83]
Right now it's hard to find in my opinion.  I believe it should be added to the top navigation bar.

**Comment by gidili** [comment]
@MichaelCurrie I don't agree with this, in the spirit of presenting only the most important links at the top, things that people are likely to be looking for when they visit the site for the first time, it seems a bit self-important to put contributor names in the most prominent spot 😂  The problem in my eyes is that you cannot put everything on the top bar. 

Maybe a way to achieve what you are suggesting could be to add a "Foundation" link that talk about the openWorm foundation, board, senior contributors and contributors. This way I think it's more relevant to have it up there, but still we need to think long and hard what to take out as we can't keep adding stuff at the top.

**Comment by MichaelCurrie** [comment]
OK
