### ISSUE TITLE
Update "Meet with us" front-page content

### ISSUE THREAD

**Issue by balicea** [openworm/org.openworm.website#95]
Concern: much of the frontpage content is out of date (e.g. references to monthly Senior Contributor meetings). Does not mention OpenWorm Foundation branding.

Solution: Update text and links according to current organizational structure and project progress.

**Comment by cheelee** [comment]
We should probably schedule a meeting some time to discuss this. Feels like there is a balance to be struck between the amount of content that needs maintenance, ease of maintenance of new content, and 1-2 people responsible for maintaining the front-page.

**Comment by geekSiddharth** [comment]
For time being, we could add links to our slack and gitter channels in the "Meet with us" section. The current text doesn't provide enough information.

**Comment by MichaelCurrie** [comment]
@geekSiddharth I agree.  I think just change the 

"Our senior contributors meet monthly in public Google Hangouts streamed via YouTube. You are welcome to join us!"

text to:

"We use Slack to communicate with us or participate in our daily activities.  You are welcome to join us!  For an invitation, fill out this form: _____" (@slarson please provide link to form)

![image](https://user-images.githubusercontent.com/5267078/27522887-2d65103c-59de-11e7-8dbc-9ccf4f46fb9a.png)

@geekSiddharth once this is done then I believe you can close this issue.

**Comment by slarson** [comment]
@geekSiddharth Here's the link to the form! https://docs.google.com/forms/d/e/1FAIpQLSdzVilyRX3z9e0PeAoQdXhBDiNXp2ugqpnT536xA2iQbLNymQ/viewform?usp=drive_web&formkey=dC1CUDQtTV82MEJJcjY0NjdCcHpYdmc6MQ#gid=0  

Thanks for doing this!
