### ISSUE TITLE
openworm.org Usability #2

### ISSUE THREAD

**Issue by balicea** [openworm/org.openworm.website#96]
Concern: based on comments from an EdTech professional, it is hard to find a clear example of what OpenWorm is all about. This person is used to simple demos as a basis for getting people excited about a project.

Solution: prominently display a link to the OpenWorm browser, or a real-time version of Gepetto. The idea is to give potential volunteers a taste of what the project artifacts ultimately look like.

**Comment by MichaelCurrie** [comment]
Currently the browser can be accessed from the prominent "Explore the Worm" button.  So I think this is okay, unless someone wants to re-open and link to a real-time version of Geppetto.

![image](https://user-images.githubusercontent.com/5267078/27638267-dc0344aa-5c3c-11e7-946a-7d5827f94f7d.png)
