### ISSUE TITLE
Add link to our Blog, readthedocs, Gitter, Slack on the front page

### ISSUE THREAD

**Issue by balicea** [openworm/org.openworm.website#97]
Concern: Information about the project is too distributed across the web (e.g. blog, readthedocs, Gitter, Slack). You can bring attention to these resources when the volunteers are being interviewed, but are invisible to casual visitors. This might discourage potential volunteers from engaging. 

Solution: provide prominent links to these resources directly on the front page of openworm.org. Use the frontpage as a gateway to educational/scientific outreach and volunteer recruitment.

**Comment by tarelli** [comment]
Slack link added, gitter is discontinued, blog is already embedded in the front page. The docs is already captured in another issue, closing this.
